    

export const GROUPE_LIST_REQUEST = 'GROUPE_LIST_REQUEST'
export const GROUPE_LIST_SUCCESS = 'GROUPE_LIST_SUCCESS'
export const GROUPE_LIST_FAIL = 'GROUPE_LIST_FAIL'
export const GROUPE_LIST_RESET  = 'GROUPE_LIST_FAIL'


export const GROUPE_DELETE_REQUEST  = 'GROUPE_DELETE_REQUEST'
export const GROUPE_DELETE_SUCCESS  = 'GROUPE_DELETE_SUCCESS'
export const GROUPE_DELETE_FAIL  = 'GROUPE_DELETE_FAIL'



export const GROUPE_ADD_REQUEST  = 'GROUPE_ADD_REQUEST'
export const GROUPE_ADD_SUCCESS  = 'GROUPE_ADD_SUCCESS'
export const GROUPE_ADD_FAIL  = 'GROUPE_ADD_FAIL'
export const GROUPE_ADD_RESET  = 'GROUPE_ADD_RESET'