


export const QUIZZ_LIST_REQUEST = 'QUIZZ_LIST_REQUEST'
export const QUIZZ_LIST_SUCCESS = 'QUIZZ_LIST_SUCCESS'
export const QUIZZ_LIST_FAIL = 'QUIZZ_LIST_FAIL'

export const QUIZZ_DETAILS_REQUEST = 'QUIZZ_DETAILS_REQUEST'
export const QUIZZ_DETAILS_SUCCESS = 'QUIZZ_DETAILS_SUCCESS'
export const QUIZZ_DETAILS_FAIL = 'QUIZZ_DETAILS_FAIL'


export const QUIZZ_DELETE_REQUEST  = 'QUIZZ_DELETE_REQUEST'
export const QUIZZ_DELETE_SUCCESS  = 'QUIZZ_DELETE_SUCCESS'
export const QUIZZ_DELETE_FAIL  = 'QUIZZ_DELETE_FAIL'


export const QUESTION_LIST_REQUEST  = 'QUESTION_LIST_REQUEST'
export const QUESTION_LIST_SUCCESS  = 'QUESTION_LIST_SUCCESS'
export const QUESTION_LIST_FAIL  = 'QUESTION_LIST_FAIL'