
/////////////////////////////// QUIZZ ////////////////////
export const QUIZZ_LIST_REQUEST = 'QUIZZ_LIST_REQUEST'
export const QUIZZ_LIST_SUCCESS = 'QUIZZ_LIST_SUCCESS'
export const QUIZZ_LIST_FAIL = 'QUIZZ_LIST_FAIL'

export const QUIZZ_DETAILS_REQUEST = 'QUIZZ_DETAILS_REQUEST'
export const QUIZZ_DETAILS_SUCCESS = 'QUIZZ_DETAILS_SUCCESS'
export const QUIZZ_DETAILS_FAIL = 'QUIZZ_DETAILS_FAIL'


export const QUIZZ_DELETE_REQUEST  = 'QUIZZ_DELETE_REQUEST'
export const QUIZZ_DELETE_SUCCESS  = 'QUIZZ_DELETE_SUCCESS'
export const QUIZZ_DELETE_FAIL  = 'QUIZZ_DELETE_FAIL'

export const QUIZZ_ADD_REQUEST  = 'QUIZZ_ADD_REQUEST'
export const QUIZZ_ADD_SUCCESS  = 'QUIZZ_ADD_SUCCESS'
export const QUIZZ_ADD_FAIL  = 'QUIZZ_ADD_FAIL'
export const QUIZZ_ADD_RESET  = 'QUIZZ_ADD_RESET'

export const QUIZZ_UPDATE_REQUEST  = 'QUIZZ_UPDATE_REQUEST'
export const QUIZZ_UPDATE_SUCCESS  = 'QUIZZ_UPDATE_SUCCESS'
export const QUIZZ_UPDATE_FAIL  = 'QUIZZ_UPDATE_FAIL'
export const QUIZZ_UPDATE_RESET  = 'QUIZZ_UPDATE_RESET'

export const QUIZZ_START_REQUEST  = 'QUIZZ_START_REQUEST'
export const QUIZZ_START_SUCCESS  = 'QUIZZ_START_SUCCESS'
export const QUIZZ_START_FAIL  = 'QUIZZ_START_FAIL'

export const QUIZZ_STOP_REQUEST  = 'QUIZZ_STOP_REQUEST'
export const QUIZZ_STOP_SUCCESS  = 'QUIZZ_STOP_SUCCESS'
export const QUIZZ_STOP_FAIL  = 'QUIZZ_STOP_FAIL'


/////////////////QUESTION//////////////////////


export const QUESTION_LIST_REQUEST  = 'QUESTION_LIST_REQUEST'
export const QUESTION_LIST_SUCCESS  = 'QUESTION_LIST_SUCCESS'
export const QUESTION_LIST_FAIL  = 'QUESTION_LIST_FAIL'


export const QUESTION_DELETE_REQUEST  = 'QUESTION_DELETE_REQUEST'
export const QUESTION_DELETE_SUCCESS  = 'QUESTION_DELETE_SUCCESS'
export const QUESTION_DELETE_FAIL  = 'QUESTION_DELETE_FAIL'
export const QUESTION_DELETE_RESET  = 'QUESTION_DELETE_RESET'



export const QUESTION_ADD_REQUEST  = 'QUESTION_ADD_REQUEST'
export const QUESTION_ADD_SUCCESS  = 'QUESTION_ADD_SUCCESS'
export const QUESTION_ADD_FAIL  = 'QUESTION_ADD_FAIL'
export const QUESTION_ADD_RESET  = 'QUESTION_ADD_RESET'


export const QUESTION_DELETE_ALL_REQUEST  = 'QUESTION_DELETE_ALL_REQUEST'
export const QUESTION_DELETE_ALL_SUCCESS  = 'QUESTION_DELETE_ALL_SUCCESS'
export const QUESTION_DELETE_ALL_FAIL  = 'QUESTION_DELETE_ALL_FAIL'
export const QUESTION_DELETE_ALL_RESET  = 'QUESTION_DELETE_ALL_RESET'

