


export const QUIZZ_LIST_REQUEST = 'QUIZZ_LIST_REQUEST'
export const QUIZZ_LIST_SUCCESS = 'QUIZZ_LIST_SUCCESS'
export const QUIZZ_LIST_FAIL = 'QUIZZ_LIST_FAIL'

export const QUIZZ_DETAILS_REQUEST = 'QUIZZ_DETAILS_REQUEST'
export const QUIZZ_DETAILS_SUCCESS = 'QUIZZ_DETAILS_SUCCESS'
export const QUIZZ_DETAILS_FAIL = 'QUIZZ_DETAILS_FAIL'