

export const QUIZZ_LIST_BYCODE_REQUEST  = 'QUIZZ_LIST_BYCODE_REQUEST'
export const QUIZZ_LIST_BYCODE_SUCCESS  = 'QUIZZ_LIST_BYCODE_SUCCESS'
export const QUIZZ_LIST_BYCODE_FAIL  = 'QUIZZ_LIST_BYCODE_FAIL'
export const QUIZZ_LIST_BYCODE_RESET  = 'QUIZZ_LIST_BYCODE_RESET'



