

export const QUIZZ_LIST_BYCODE_REQUEST  = 'QUIZZ_LIST_BYCODE_REQUEST'
export const QUIZZ_LIST_BYCODE_SUCCESS  = 'QUIZZ_LIST_BYCODE_SUCCESS'
export const QUIZZ_LIST_BYCODE_FAIL  = 'QUIZZ_LIST_BYCODE_FAIL'
export const QUIZZ_LIST_BYCODE_RESET  = 'QUIZZ_LIST_BYCODE_RESET'



export const REPONSE_ADD_REQUEST  = 'REPONSE_ADD_REQUEST'
export const REPONSE_ADD_SUCCESS  = 'REPONSE_ADD_SUCCESS'
export const REPONSE_ADD_FAIL  = 'REPONSE_ADD_FAIL'


export const REPONSE_GET_BY_QUIZZID_REQUEST  = 'REPONSE_GET_BY_QUIZZID_REQUEST'
export const REPONSE_GET_BY_QUIZZID_SUCCESS  = 'REPONSE_GET_BY_QUIZZID_SUCCESS'
export const REPONSE_GET_BY_QUIZZID_FAIL  = 'REPONSE_GET_BY_QUIZZID_FAIL'


export const REPONSE_GET_BY_QUESTIONID_REQUEST  = 'REPONSE_GET_BY_QUESTIONID_REQUEST'
export const REPONSE_GET_BY_QUESTIONID_SUCCESS  = 'REPONSE_GET_BY_QUESTIONID_SUCCESS'
export const REPONSE_GET_BY_QUESTIONID_FAIL  = 'REPONSE_GET_BY_QUESTIONID_FAIL'








